<?php
$currency_code_array = array
			(
			array( "ALL",8,"LEK",2),
			array( "DZD",12,"ALGERIAN DINAR",2),
			array( "AON",24,"ANGOLA KWANZA",2),
			array( "ARS",32,"ARGENTINE PESO",2),
			array( "AUD",36,"AUSTRALIAN DOLLAR",2),
			array( "BSD",44,"BAHAMIAN DOLLAR",2),
			array( "BHD",48,"BAHRAINI DINAR",3),
			array( "BDT",50,"TAKA",2),
			array( "AMD",51,"DRAM",2),
			array( "BBD",52,"BARBADOS DOLLAR",2),
			array( "BMD",60,"BERMUDAN DOLLAR",2),
			array( "BTN",64,"NGULTRUM",2),
			array( "BOB",68,"BOLIVIAN PESO",2),
			array( "BAM",70,"DINAR",0),
			array( "BWP",72,"PULA",2),
			array( "BRC",76,"CRUZEIRO",2),
			array( "BZD",84,"BELIZE DOLLAR",2),
			array( "SBD",90,"SOLOMON ISLANDS DOLLAR",2),
			array( "BND",96,"BRUNEI DOLLAR",2),
			array( "BUK",104,"KYAT",2),
			array( "BIF",108,"BURUNDI FRANC",2),
			array( "BYB",112,"BELARRUSIAN RUBLE",0),
			array( "KHR",116,"RIEL",2),
			array( "CAD",124,"CANADIAN DOLLAR",2),
			array( "CVE",132,"CAPE VERDE ESCUDO",2),
			array( "KYD",136,"CAYMAN ISLANDS DOLLAR",2),
			array( "LKR",144,"SRI LANKA RUPEE",2),
			array( "CLP",152,"CHILEAN PESO",2),
			array( "CNY",156,"YUAN RENMINBI",2),
			array( "CNH",157,"CHINESE RENMIMBI",2),
			array( "CNX",158,"CHINESE RENMINBI",2),
			array( "COP",170,"COLOMBIAN PESO",2),
			array( "KMF",174,"COMORO FRANC",0),
			array( "CRC",188,"COSTA RICAN COLON",2),
			array( "HRK",191,"CROATIAN KUNA",2),
			array( "CUP",192,"CUBAN PESO",2),
			array( "CYP",196,"CYPRUS POUND",2),
			array( "CSK",200,"KORUNA",2),
			array( "CZK",203,"CZECH KORUNA",2),
			array( "DKK",208,"DANISH KRONE",2),
			array( "DOP",214,"DOMINICAN PESO",2),
			array( "SVC",222,"EL SALVADOR COLON",2),
			array( "ETB",230,"ETHIOPIAN BIRR",2),
			array( "ERN",232,"ERITREAN NAKTAN",2),
			array( "EEK",233,"ESTONIAN KROON",2),
			array( "FKP",238,"FALKLAND ISLANDS",2),
			array( "FJD",242,"FIJI DOLLAR",2),
			array( "DJF",262,"DJIBOUTI FRANC",0),
			array( "GMD",270,"DALASI",2),
			array( "GHC",288,"CHANA CEDI",2),
			array( "GIP",292,"GIBRALTAR POUND",2),
			array( "GTQ",320,"QUETZAL",2),
			array( "GNF",324,"SYLI",0),
			array( "GYD",328,"GUYANA DOLLAR",2),
			array( "HTG",332,"GOURDE",2),
			array( "HNL",340,"SEMPIRA",2),
			array( "HKD",344,"HONG KONG DOLLAR",2),
			array( "HUF",348,"FORINT",2),
			array( "ISK",352,"ICELAND KRONA",2),
			array( "INR",356,"INDIAN RUPEE",2),
			array( "IDR",360,"RUPIAH",0),
			array( "IRR",364,"IRANIAN RIAL",2),
			array( "IRA",365,"IRANIAN AIRLINE RATE",2),
			array( "IQD",368,"IRAQI DINAR",3),
			array( "ILS",376,"ISRAEL SHEKEL",2),
			array( "JMD",388,"JAMAICAN DOLLAR",2),
			array( "JPY",392,"YEN",0),
			array( "KZT",398,"TENGE",2),
			array( "JOD",400,"JORDANIAN DINAR",3),
			array( "KES",404,"KENYAN SHILLING",2),
			array( "KPW",408,"NORTH KOREAN WON",2),
			array( "KRW",410,"KOREAN WON",0),
			array( "KWD",414,"KUWAITI DINAR",3),
			array( "KGS",417,"SOM",2),
			array( "LAK",418,"KIP",2),
			array( "LBP",422,"LEBANESE POUND",2),
			array( "LSL",426,"LESOTHO LOTI",2),
			array( "LVL",428,"LATVIAN LAT",2),
			array( "LRD",430,"LIBERIAN DOLLAR",2),
			array( "LYD",434,"LIBYAN DINAR",3),
			array( "LTL",440,"LITHUANIAN LITAS",2),
			array( "MOP",446,"MACAU PATACAS",2),
			array( "MGF",450,"MALAGASY FRANC",0),
			array( "MWK",454,"MALAWI KWACHA",2),
			array( "MYR",458,"MALAYSIAN RINGGIT",2),
			array( "MVR",462,"MALDIVE RUPEE",2),
			array( "MLF",466,"MALI",2),
			array( "MTL",470,"MALTESE LIRA",2),
			array( "MRO",478,"OUGUIYA",2),
			array( "MUR",480,"MAURITIUS RUPEE",2),
			array( "MXN",484,"MEXICAN PESO",2),
			array( "MNT",496,"TUGRIK",2),
			array( "MDL",498,"MOLDOVAN LEU",2),
			array( "MAD",504,"MARROCCAN DIRHAM",2),
			array( "OMR",512,"RIAL OMANI",3),
			array( "NAD",516,"NAMIBIAN DOLLAR",2),
			array( "NPR",524,"NEPALESE RUPEE",2),
			array( "ANG",532,"NETHERLANDS ANTILLIA",2),
			array( "AWG",533,"ARUBAN GUILDER",2),
			array( "NTZ",536,"YUGOSLAVIAN NEW DIAN",2),
			array( "VUV",548,"VATU",0),
			array( "NZD",554,"NEW ZEALAND DOLLAR",2),
			array( "566",556,"NAIRA",2),
			array( "NIO",558,"CORDOBA",2),
			array( "NGN",566,"NAIRA",2),
			array( "NOK",578,"NORWEGIAN KRONE",2),
			array( "PCI",582,"PACIFIC ISLAND",0),
			array( "PKR",586,"PAKISTAN RUPEE",2),
			array( "PAB",590,"BALBOA",2),
			array( "PGK",598,"KINA",2),
			array( "PYG",600,"GUARANI",0),
			array( "PEN",604,"PERU INTI",2),
			array( "PHP",608,"PHILIPPINE PESO",2),
			array( "GWP",624,"GUINEA-BISSAU PESO",2),
			array( "TPE",626,"TIMOR ESCUDO",0),
			array( "QAR",634,"QATARI RIAL",2),
			array( "RUB",643,"RUSSIAN ROUBLE",2),
			array( "RWF",646,"RWANDA FRANC",0),
			array( "SHP",654,"ST. HELENA POUND",2),
			array( "STD",678,"DOBRA",2),
			array( "SAR",682,"SAUDI RIYAL",2),
			array( "SCR",690,"SEYCHELLES RUPEE",2),
			array( "SLL",694,"LEONE",2),
			array( "SGD",702,"SINGAPORE DOLLAR",2),
			array( "VND",704,"DONG",0),
			array( "SIT",705,"SLOVENIAN TOLAR",2),
			array( "SOS",706,"SOMALI SHILLING",2),
			array( "ZAR",710,"RAND",2),
			array( "ZWD",716,"ZIMBABWE DOLLAR",2),
			array( "YDD",720,"YEMENI DINAR",2),
			array( "SDP",736,"SUDANESE POUND",2),
			array( "SDA",737,"SUDAN AIRLINES",2),
			array( "SZL",748,"LILANGENI",2),
			array( "SEK",752,"SWEDISH KRONA",2),
			array( "CHF",756,"SWISS FRANC",2),
			array( "SYP",760,"SYRIAN POUND",2),
			array( "TJR",762,"TAJIK RUBLE",0),
			array( "THB",764,"BAHT",2),
			array( "TOP",776,"PA'ANGA",2),
			array( "TTD",780,"TRINIDAD AND TOBAGO",2),
			array( "AED",784,"UAE DIRHAM",2),
			array( "TND",788,"TUNISIAN DINAR",3),
			array( "PTL",793,"TURKISH LIRA",0),
			array( "TMM",795,"MANAT",2),
			array( "UGS",800,"UGANDA SHILLING",2),
			array( "UAK",804,"KARBOVANET",2),
			array( "MKD",807,"MACEDONIAN DENAR",2),
			array( "EGP",818,"EGYPTIAN POUND",2),
			array( "GBP",826,"POUND STERLING",2),
			array( "TZS",834,"TANZANIAN SHILLING",2),
			array( "USD",840,"US DOLLAR",2),
			array( "UYU",858,"URUGUAYAN PESO",2),
			array( "UZS",860,"UZBEKISTAN SUM",2),
			array( "WST",882,"TALA",2),
			array( "YER",886,"YEMINI RIAL",2),
			array( "CSD",891,"SERBIAN DINAR",2),
			array( "ZMK",894,"KWACHA",2),
			array( "TWD",901,"NEW TAIWAN DOLLAR",2),
			array( "TMT",934,"NEW MANAT",2),
			array( "GHS",936,"GHANA CEDI",2),
			array( "VEF",937,"BOLIVAR FUERTE",2),
			array( "RSD",941,"DINAR SERBIO",2),
			array( "MZN",943,"MOZAMBIQUE METICAL (NEW)",2),
			array( "AZN",944,"AZERBAIJANIAN MANAT_(NEW)",2),
			array( "RON",946,"NEW LEU",2),
			array( "TRY",949,"TURKISH LIRA",2),
			array( "XAF",950,"CFA FRANC BEAC",0),
			array( "XCD",951,"EAST CARIBBEAN DOLLAR",2),
			array( "XOF",952,"CFA FRANC BCEAO",0),
			array( "XPF",953,"CFP FRANC",0),
			array( "XEU",954,"EUROPEAN CURRENCY UNITED",2),
			array( "SRD",968,"SURINAME DOLLAR",2),
			array( "MGA",969,"ARIARY",2),
			array( "AFN",971,"AFGHANISTAN AFGHANI",2),
			array( "TJS",972,"TAJIKISTAN SOMONI",2),
			array( "AOA",973,"KWANZA ANGOLA",2),
			array( "BYR",974,"BELARUSSIAN RUBLE REVALORIZADO",0),
			array( "BGN",975,"NEW LEV",2),
			array( "CDF",976,"FRANCO DEL CONGO",2),
			array( "BAM",977,"BOSNIAN MARKA",2),
			array( "EUR",978,"EURO",2),
			array( "UAH",980,"UKRAINIAN HRYVNIA",2),
			array( "GEL",981,"LARI",2),
			array( "PLN",985,"NEW POLISH SLOTY",2),
			array( "BRL",986,"BRAZILIAN REAL",2),
			array( "ESB",995,"PESETA ESPA#OLA CONVERTIBLE",0)
			);