<?php

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Exit if accessed directly
}
/**
 * Generated by the WordPress Meta Box generator
 * at http://jeremyhixon.com/tool/wordpress-meta-box-generator/
 */

function caixabank_order_metabox_get_meta( $value ) {
	global $post;

	$field = get_post_meta( $post->ID, $value, true );
	if ( ! empty( $field ) ) {
		return is_array( $field ) ? stripslashes_deep( $field ) : stripslashes( wp_kses_decode_entities( $field ) );
	} else {
		return false;
	}
}

function caixabank_order_metabox_add_meta_box() {
	add_meta_box(
		'caixabank_order_metabox-caixabank-order-metabox',
		__( 'caixabank Order Data', 'caixabank_order_metabox' ),
		'caixabank_order_metabox_html',
		'caixabank_orders',
		'normal',
		'default'
	);
}
add_action( 'add_meta_boxes', 'caixabank_order_metabox_add_meta_box' );

function caixabank_order_metabox_html( $post) {
	wp_nonce_field( '_caixabank_order_metabox_nonce', 'caixabank_order_metabox_nonce' ); ?>

	<p>Opciones ejemplo</p>

	<p>
		<label for="_caixabank_order_metabox_description"><?php _e( 'Description', 'caixabank_order_metabox' ); ?></label><br>
		<input type="text" name="_caixabank_order_metabox_description" id="_caixabank_order_metabox_description" value="<?php echo caixabank_order_metabox_get_meta( '_caixabank_order_metabox_description' ); ?>">
	</p><?php
}

function caixabank_order_metabox_save( $post_id ) {
	if ( defined( 'DOING_AUTOSAVE' ) && DOING_AUTOSAVE ) return;
	if ( ! isset( $_POST['caixabank_order_metabox_nonce'] ) || ! wp_verify_nonce( $_POST['caixabank_order_metabox_nonce'], '_caixabank_order_metabox_nonce' ) ) return;
	if ( ! current_user_can( 'edit_post', $post_id ) ) return;

	if ( isset( $_POST['_caixabank_order_metabox_description'] ) )
		update_post_meta( $post_id, '_caixabank_order_metabox_description', esc_attr( $_POST['_caixabank_order_metabox_description'] ) );
}
add_action( 'save_post', 'caixabank_order_metabox_save' );

/*
	Usage: caixabank_order_metabox_get_meta( '_caixabank_order_metabox_description' )
*/
?>