<?php

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Exit if accessed directly
}

/**
 * Generated by the WordPress Meta Box Generator at http://goo.gl/8nwllb
 */
class Caixabank_Meta_Box {
	private $screens = array(
		'caixabank_orders',
	);
	private $fields = array(
		array(
			'id' => 'caixabank_description',
			'label' => 'Description',
			'type' => 'textarea',
		),
		array(
			'id' => 'caixabank_tipo_pago',
			'label' => 'Tipo pago',
			'type' => 'text',
		),
		array(
			'id' => 'caixabank_price',
			'label' => 'Price',
			'type' => 'number',
		),
		array(
			'id' => 'caixabank_estado_pago',
			'label' => 'Estado pago',
			'type' => 'text',
		),
		array(
			'id' => 'caixabank_username_realiza_pago',
			'label' => 'Username',
			'type' => 'text',
		),
		array(
			'id' => 'caixabank_user_id_realiza_pago',
			'label' => 'User ID',
			'type' => 'text',
		),
		array(
			'id' => 'caixabank_nombre_apellidos_realiza_pago',
			'label' => 'Apellidos',
			'type' => 'text',
		),
		array(
			'id' => 'caixabank_email_realiza_pago',
			'label' => 'email',
			'type' => 'text',
		),
		array(
			'id' => 'caixabank_dni_realiza_pago',
			'label' => 'DNI',
			'type' => 'text',
		),
		array(
			'id' => 'caixabank_company_realiza_pago',
			'label' => 'Company Name',
			'type' => 'text',
		),
		array(
			'id' => 'caixabank_adress_1_realiza_pago',
			'label' => 'Adress 1',
			'type' => 'textarea',
		),
		array(
			'id' => 'caixabank_adress_2_realiza_pago',
			'label' => 'Adress 2',
			'type' => 'textarea',
		),
		array(
			'id' => 'caixabank_tax_status_realiza_pago',
			'label' => 'Tipo usuario',
			'type' => 'text',
		),
		array(
			'id' => 'caixabank_city_realiza_pago',
			'label' => 'City',
			'type' => 'text',
		),
		array(
			'id' => 'caixabank_post_code_realiza_pago',
			'label' => 'Postal Code',
			'type' => 'text',
		),
		array(
			'id' => 'caixabank_country_realiza_pago',
			'label' => 'Country',
			'type' => 'text',
		),
		array(
			'id' => 'caixabank_state_county_realiza_pago',
			'label' => 'State',
			'type' => 'text',
		),
		array(
			'id' => 'caixabank_state_county_outsite_spain_realiza_pago',
			'label' => 'State outsite Spain',
			'type' => 'text',
		),
		array(
			'id' => 'caixabank_telephone_realiza_pago',
			'label' => 'Telephone',
			'type' => 'text',
		),
		array(
			'id' => 'caixabank_mobile_realiza_pago',
			'label' => 'Mobile',
			'type' => 'text',
		),
		array(
			'id' => 'caixabank_use_tax',
			'label' => 'Use TAX',
			'type' => 'checkbox',
		),
		array(
			'id' => 'caixabank_use_irpf',
			'label' => 'Use IRPF',
			'type' => 'checkbox',
		),
		array(
			'id' => 'caixabank_custom_iva_realiza_pago',
			'label' => 'TAX',
			'type' => 'number',
		),
		array(
			'id' => 'caixabank_custom_irpf_realiza_pago',
			'label' => 'IRPF',
			'type' => 'number',
		),
		array(
			'id' => 'caixabank_date',
			'label' => 'Date',
			'type' => 'date',
		),
		array(
			'id' => 'caixabank_time',
			'label' => 'Time',
			'type' => 'time',
		),
	);

	/**
	 * Class construct method. Adds actions to their respective WordPress hooks.
	 */
	public function __construct() {
		add_action( 'add_meta_boxes', array( $this, 'add_meta_boxes' ) );
		add_action( 'save_post', array( $this, 'save_post' ) );
	}

	/**
	 * Hooks into WordPress' add_meta_boxes function.
	 * Goes through screens (post types) and adds the meta box.
	 */
	public function add_meta_boxes() {
		foreach ( $this->screens as $screen ) {
			add_meta_box(
				'caixabank-order-metabox',
				__( 'Order', 'caixabank-tools-official' ),
				array( $this, 'add_meta_box_callback' ),
				$screen,
				'advanced',
				'default'
			);
		}
	}

	/**
	 * Generates the HTML for the meta box
	 *
	 * @param object $post WordPress post object
	 */
	public function add_meta_box_callback( $post ) {
		wp_nonce_field( 'caixabank_order_metabox_data', 'caixabank_order_metabox_nonce' );
		$this->generate_fields( $post );
	}

	/**
	 * Generates the field's HTML for the meta box.
	 */
	public function generate_fields( $post ) {
		$output = '';
		foreach ( $this->fields as $field ) {
			$label = '<label for="' . $field['id'] . '">' . $field['label'] . '</label>';
			$db_value = get_post_meta( $post->ID, '_' . $field['id'], true );
			switch ( $field['type'] ) {
				case 'checkbox':
					$input = sprintf(
						'<input %s id="%s" name="%s" type="checkbox" value="1">',
						$db_value === '1' ? 'checked' : '',
						$field['id'],
						$field['id']
					);
					break;
				case 'textarea':
					$input = sprintf(
						'<textarea class="large-text" id="%s" name="%s" rows="5">%s</textarea>',
						$field['id'],
						$field['id'],
						$db_value
					);
					break;
				default:
					$input = sprintf(
						'<input %s id="%s" name="%s" type="%s" value="%s">',
						$field['type'] !== 'color' ? 'class="regular-text"' : '',
						$field['id'],
						$field['id'],
						$field['type'],
						$db_value
					);
			}
			$output .= $this->row_format( $label, $input );
		}
		echo '<table class="form-table"><tbody>' . $output . '</tbody></table>';
	}

	/**
	 * Generates the HTML for table rows.
	 */
	public function row_format( $label, $input ) {
		return sprintf(
			'<tr><th scope="row">%s</th><td>%s</td></tr>',
			$label,
			$input
		);
	}
	/**
	 * Hooks into WordPress' save_post function
	 */
	public function save_post( $post_id ) {
		if ( ! isset( $_POST['caixabank_order_metabox_nonce'] ) )
			return $post_id;

		$nonce = $_POST['caixabank_order_metabox_nonce'];
		if ( !wp_verify_nonce( $nonce, 'caixabank_order_metabox_data' ) )
			return $post_id;

		if ( defined( 'DOING_AUTOSAVE' ) && DOING_AUTOSAVE )
			return $post_id;

		foreach ( $this->fields as $field ) {
			if ( isset( $_POST[ $field['id'] ] ) ) {
				switch ( $field['type'] ) {
					case 'email':
						$_POST[ $field['id'] ] = sanitize_email( $_POST[ $field['id'] ] );
						break;
					case 'text':
						$_POST[ $field['id'] ] = sanitize_text_field( $_POST[ $field['id'] ] );
						break;
				}
				update_post_meta( $post_id, '_' . $field['id'], $_POST[ $field['id'] ] );
			} else if ( $field['type'] === 'checkbox' ) {
				update_post_meta( $post_id, '_' . $field['id'], '0' );
			}
		}
	}
}
new Caixabank_Meta_Box;